interface CraftingComponent {
  name: string;
  description: string;
  cost?: string;
}

const craftingComponents: { [key: string]: CraftingComponent[] } = {
  Consumables: [
    { name: "Acid", description: "Used in various alchemical processes and as a corrosive substance." },
    { name: "Alchemist’s Fire", description: "A sticky, flammable substance used to create fire." },
    { name: "Antitoxin", description: "Used to neutralize poisons in the body." },
    { name: "Oil", description: "A flammable liquid used for lamps, creating fire, and other purposes." },
    { name: "Paper", description: "Used for writing and creating documents or scrolls." },
    { name: "Perfume", description: "Used for enhancing smells or masking odors." },
    { name: "Rations", description: "Food supplies for travel and sustenance." },
    { name: "Ink", description: "Used for writing and drawing." },
    { name: "Spell Scroll", description: "A scroll containing a single spell, allowing it to be cast once." },
    { name: "Firearm Bullets", description: "Ammunition for firearms." },
    { name: "Sling Bullets", description: "Ammunition for slings." },
    { name: "Arrows", description: "Ammunition for bows." },
    { name: "Bolts", description: "Ammunition for crossbows." },
  ],
  Equipment: [
    { name: "Component Pouch", description: "A pouch to hold material components for spells." },
    { name: "Club", description: "A simple melee weapon." },
    { name: "Greatclub", description: "A simple melee weapon." },
    { name: "Quarterstaff", description: "A versatile melee weapon." },
    { name: "Barrel", description: "A container for storing liquids or other goods." },
    { name: "Chest", description: "A container for storing items." },
    { name: "Ladder", description: "Used for climbing." },
    { name: "Pole", description: "A long, sturdy pole with various uses." },
    { name: "Portable Ram", description: "Used for breaking down doors." },
    { name: "Torch", description: "A light source." },
    { name: "Map", description: "A representation of a geographical area." },
    { name: "Climber’s Kit", description: "Equipment for climbing." },
    { name: "Glass Bottle", description: "A container made of glass." },
    { name: "Magnifying Glass", description: "Used to make small objects appear larger." },
    { name: "Spyglass", description: "Used to view distant objects." },
    { name: "Vial", description: "A small container, often made of glass." },
    { name: "Arcane Focus", description: "An item used as a focus for spellcasting by some classes." },
    { name: "Holy Symbol", description: "An item representing a deity, used as a focus for spellcasting by clerics and paladins." },
    { name: "Sling", description: "A simple ranged weapon." },
    { name: "Whip", description: "A martial melee weapon." },
    { name: "Hide Armor", description: "Light armor made from animal hides." },
    { name: "Leather Armor", description: "Light armor made from leather." },
    { name: "Studded Leather Armor", description: "Light armor made from leather with metal studs." },
    { name: "Backpack", description: "Used for carrying gear." },
    { name: "Crossbow Bolt Case", description: "A case for carrying crossbow bolts." },
    { name: "Map or Scroll Case", description: "A case for carrying maps or scrolls." },
    { name: "Parchment", description: "Material for writing." },
    { name: "Pouch", description: "A small bag for carrying items." },
    { name: "Quiver", description: "A container for carrying arrows." },
    { name: "Waterskin", description: "A container for carrying water." },
    { name: "Block and Tackle", description: "A pulley system for lifting heavy objects." },
    { name: "Jug", description: "A container for liquids." },
    { name: "Lamp", description: "A light source." },
    { name: "Any Melee weapon (except Club, Greatclub, Quarterstaff, and Whip)", description: "Various melee weapons." },
    { name: "Medium armor (except Hide)", description: "Various medium armor types." },
    { name: "Heavy armor", description: "Various heavy armor types." },
    { name: "Ball Bearings", description: "Small metal balls used as a hazard or in traps." },
    { name: "Bucket", description: "A container for carrying liquids or other materials." },
    { name: "Caltrops", description: "Sharp metal spikes used to injure feet." },
    { name: "Chain", description: "A length of chain with various uses." },
    { name: "Crowbar", description: "A tool for prying or forcing things open." },
    { name: "Grappling Hook", description: "A hook attached to a rope for climbing or pulling." },
    { name: "Iron Pot", description: "A cooking pot made of iron." },
    { name: "Iron Spikes", description: "Sharp spikes used for various purposes." },
    { name: "Musket", description: "A ranged weapon." },
    { name: "Pistol", description: "A ranged weapon." },
    { name: "Bell", description: "An instrument that produces a ringing sound." },
    { name: "Bullseye Lantern", description: "A lantern with an adjustable beam." },
    { name: "Flask", description: "A container, often for liquids." },
    { name: "Hooded Lantern", description: "A lantern with a shutter to control light." },
    { name: "Hunting Trap", description: "A trap for catching animals." },
    { name: "Lock", description: "A mechanism for securing doors or containers." },
    { name: "Manacles", description: "Restraints for hands or feet." },
    { name: "Mirror", description: "A reflective surface." },
    { name: "Shovel", description: "A tool for digging." },
    { name: "Signal Whistle", description: "Used for making a loud sound to signal others." },
    { name: "Tinderbox", description: "Used for starting fires." },
    { name: "Padded Armor", description: "Light armor made from padded cloth." },
    { name: "Basket", description: "A container made from woven material." },
    { name: "Bedroll", description: "A portable sleeping mat." },
    { name: "Blanket", description: "A covering for warmth." },
    { name: "Fine Clothes", description: "High-quality clothing." },
    { name: "Net", description: "Used to trap or restrain." },
    { name: "Robe", description: "A loose-fitting outer garment." },
    { name: "Rope", description: "A length of strong cord." },
    { name: "Sack", description: "A bag for carrying goods." },
    { name: "String", description: "A thin cord with various uses." },
    { name: "Tent", description: "A portable shelter." },
    { name: "Traveler's Clothes", description: "Durable and practical clothing for travel." },
    { name: "Ranged weapons (except Pistol, Musket, and Sling)", description: "Various ranged weapons." },
    { name: "Needles", description: "Sharp pointed objects used for sewing or other tasks." },
  ],
  Crafting: [
    { name: "Leather", description: "Animal hide used for making armor and other items.", cost: "2 sp" },
    { name: "Iron Ingot", description: "A basic material for blacksmithing.", cost: "1 gp" },
    { name: "Wood", description: "Used for crafting various wooden items.", cost: "1 cp per pound" },
    { name: "Cloth", description: "Fabric used for clothing and other textiles.", cost: "5 sp per yard" },
  ],
};
export default craftingComponents;